<template>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>&copy; Lynxmasters 2018</strong>
      </p>

      <a class="button is-text" @click="isLegalDisclaimer = true">Legal Disclaimer</a>
      <a class="button is-text" @click="isPrivacyPolicy = true">Privacy Policy</a>

      <!-- Legal Disclaimer Modal -->
      <b-modal :active.sync="isLegalDisclaimer" :width="640" scroll="keep">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title is-centered">Legal Disclaimer</p>
          </header>
          <div class="card-content">
            <div class="content">
              <h1>Disclaimer</h1>

              <p><strong>Last updated:</strong> August 11, 2018</p>

              <p>The information contained on http://www.lynxmasters.com website (the "Service") is for general information purposes only.</p>

              <p><strong>Lynxmasters</strong> assumes no responsibility for errors or omissions in the contents on the Service.</p>

              <p>In no event shall <strong>Lynxmasters</strong> be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. <strong>Lynxmasters</strong> reserves the right to make additions, deletions, or modification to the contents on the Service at any time without prior notice. This Disclaimer for <strong>Lynxmasters</strong> is <a href="https://termsfeed.com/disclaimer/generator/">generated by TermsFeed</a></p>

              <p><strong>Lynxmasters</strong> does not warrant that the website is free of viruses or other harmful components.</p>

              <h2>External links disclaimer</h2>

              <p>http://www.lynxmasters.com website may contain links to external websites that are not provided or maintained by or in any way affiliated with Lynxmasters</p>

              <p>Please note that the <strong>Lynxmasters</strong> does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.</p>
            </div>
          </div>
        </div>
      </b-modal>
      <!-- End Legal Disclaimer Modal -->

      <!-- Privacy Policy Modal -->
      <b-modal :active.sync="isPrivacyPolicy" :width="640" scroll="keep">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title is-centered">Privacy Policy</p>
          </header>
          <div class="card-content">
            <div class="content">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Phasellus nec iaculis mauris. <a>@bulmaio</a>.
              <a>#css</a> <a>#responsive</a>
              <br>
              <small><strong>Last Updated:</strong> 11:09 PM - 1 Jan 2016</small>
            </div>
          </div>
        </div>
      </b-modal>
      <!-- End Privacy Policy Modal -->
    </div>
  </footer>
</template>

<script>
  export default {
    name: 'Footer',
    data() {
      return {
        isLegalDisclaimer: false,
        isPrivacyPolicy: false
      }
    }
  }
</script>

<style scoped>

</style>
